### ISSUE TITLE
Playback Speed Functionality

### ISSUE THREAD

**Issue by hzlgnn** [brim-borium/spotify_sdk#148]
Hello,

Do you have any plans to add speed functionality to this package?

Thank you,

**Comment by brim-borium** [comment]
Hi @hzlgnn do you mean specific for Podcasts?

**Comment by hzlgnn** [comment]
Yes

**Comment by brim-borium** [comment]
@hzlgnn just opened a PR for this were I implemented it for Android, iOS is still tbd

**Comment by brim-borium** [comment]
Update on that I manage to implement his for Android, **but** it seems that Spotify itself does not support this at the moment. Because when I am testing this I always get the following error: 

`com.spotify.protocol.client.error.RemoteClientException: {"message":"Playback speed can only be set on local device"}` Therefore this seems to be a problem we can't fix with this plugin at the moment. So this issue will be closed for now.

**Comment by brim-borium** [comment]
Reopening because I made a mistake. New version will be released shortly

**Comment by brim-borium** [comment]
This has been implemented for android for version 3.0.0-dev.2
