### ISSUE TITLE
Auth for android

### ISSUE THREAD

**Issue by Nirmitjatana** [brim-borium/spotify_sdk#99]
I am getting this issue, while trying to run the app. I am only using auth service as of now

**Screenshots**
![image](https://user-images.githubusercontent.com/52108077/117544269-45c60b80-b03e-11eb-8b4d-dfef10babbfd.png)

**Comment by brim-borium** [comment]
@Nirmitjatana it seems that you didn't add all modules, you have to add auth and appremote. Follow the instructions from the readme, especially this part from https://developer.spotify.com/documentation/android/quick-start/

**Comment by irfan-429** [comment]
When I tried with the old version of Android Studio where it have option to add .jar/.aar files via the dialogue it worked successfully.

**Comment by andriy-gulak-ew** [comment]
I've faced the same problem on Android Studio 4.2. Is there any solution to this problem?

**Comment by andriy-gulak-ew** [comment]
I've found a solution/workaround. If you are on Android Studio 4.2+ you need to manually do all the things that the option to add .jar/.aar files did via the dialogue:
1. Open the android folder of your flutter project as an Android Studio project
2. In the android root folder create 2 folders spotify-app-remote and spotify-auth and place the corresponding aar files and create empty build.gradle files, like on the screenshot below:
![image](https://user-images.githubusercontent.com/42183561/125422846-24e03bf0-ec7f-409f-b382-0ef2d0213d08.png)
3.  Content of the spotify-app-remote/build.gradle file:
```
configurations.maybeCreate("default")
artifacts.add("default", file('spotify-app-remote-release-0.7.1.aar'))
```
4. Content of the spotify-auth/build.gradle file:
```
configurations.maybeCreate("default")
artifacts.add("default", file('spotify-auth-release-1.2.3.aar'))
```
5. In the android root folder find settings.gradle file, open it and add the following line at the top of the file:
```
include ':spotify-auth'
include ':spotify-app-remote'
```
6. That's all! Now build your flutter app!

**Comment by andriy-gulak-ew** [comment]
@brim-borium 
Yes, it can be part of the package, but in this case, you have to take care of spotify-app-remote and spotify-auth aar versions under the hood of your plugin which is not ideal.

**Comment by brim-borium** [comment]
@brim-borium reminder to add this solution to the documentation

**Comment by YasinCelikSoftware** [comment]
I tried that solution because I am getting "Direct local .aar file dependencies are not supported" error. But didn't worked for me. Here what I do:
1. I created a folder in android folder.
![image](https://github.com/brim-borium/spotify_sdk/assets/107568842/a88e2e6b-a821-47e5-8342-ee11d59e8dda)

2. I copied .aar file into that folder. And created an empty build.gradle file. And put the provided configuration code inside build.gradle file.
![image](https://github.com/brim-borium/spotify_sdk/assets/107568842/f2cfbed1-1858-4183-9f99-308ab05510c9)

3. Then I edit my settings.gradle file like this (line 7).
![image](https://github.com/brim-borium/spotify_sdk/assets/107568842/2aed3df8-52f5-4f3b-b41d-f9c7f6e88aaf)

But still getting the error. "Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the...."
